In [17]:
#This Link is Important: https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/3 
#Link to Tutorial I followed: https://www.youtube.com/watch?v=SSW9LzOJSus&ab_channel=NicholasRenotte 

In [18]:
!pip install tensorflow==2.10.0 opencv-python matplotlib

In [19]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [20]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
#interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_thunder_3.tflite')
interpreter.allocate_tensors()

In [21]:
#Ignore, just for testing
interpreter.get_input_details()

[{'name': 'serving_default_input:0',
  'index': 0,
  'shape': array([  1, 192, 192,   3]),
  'shape_signature': array([  1, 192, 192,   3]),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [22]:
print(192 in interpreter.get_input_details()[0]['shape']) #For testing only

True


In [23]:
#Ignore, just for testing
interpreter.get_output_details()

[{'name': 'StatefulPartitionedCall:0',
  'index': 312,
  'shape': array([ 1,  1, 17,  3]),
  'shape_signature': array([ 1,  1, 17,  3]),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [24]:
#Drawing Keypoints

def draw_keypoints(frame, keypoints, confidence):
    """
    Draws in the locations of the key joints
    """
    y, x, c = frame.shape #y coordinate, x, coordginate, the channel coordinate
    shaped = np.squeeze(np.multiply(keypoints, [y, x, 1])) #the third coordinate in our keypoints is the confidence value, so we multiply by one to maintain that coordinate
    
    for kp in shaped:
        ky, kx, kp_conf = kp #extracting our y, our x, 
        if kp_conf > confidence:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0, 255, 0), -1) #last three parameters are size, color, fill
    

In [25]:
#Dictionary that represents the connections for the function below
# the value is the letter that corresponds to the color of the edge (they are just here, we are not really using them)
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [26]:
#Drawing Edges

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape #y coordinate, x, coordginate, the channel coordinate
    shaped = np.squeeze(np.multiply(keypoints, [y, x, 1])) #the third coordinate in our keypoints is the confidence value, so we multiply by one to maintain that coordinate
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (255, 0, 0), 2)

In [27]:
#Making Detections

cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    #Need to reshape image. Movenet Architecture expects an image of dimensions 192x192x3
    img = frame.copy() #makes a copy of the captured frame and saves it to a variable 'img'
    #to resize, we need to encapsulate it inside another array (that's what expand_dims does)
    #the resizing happens with the resize_with_pad function, where we give it the proper dimensions. 
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192, 192) #For Lightning
    #img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 256, 256) #For Thunder

    #Image needs to be represented as a float32 tensor, that is what the below line does
    input_image = tf.cast(img, dtype=tf.float32)
    
    
    #Set input and Output (using the TF interpreter)
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    #Make Predictions
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image)) #Setting input details equal to input image
    interpreter.invoke() #invoking (making) our prediction
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index']) # getting output details
    print(keypoints_with_scores)
    
    #Rendering
    draw_connections(frame, keypoints_with_scores, EDGES, 0.5)
    draw_keypoints(frame, keypoints_with_scores, 0.5)
    
    #this tiny snippet is just for naming the camera properly based on the model we r using lol
    if 192 in interpreter.get_input_details()[0]['shape']:
        cv2.imshow('MoveNet Lightning', frame)
    if 256 in interpreter.get_input_details()[0]['shape']:
        cv2.imshow('MoveNet Thunder', frame)
    #Exiting the Camera (Press q)
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[[[0.3271464  0.4718657  0.71926904]
   [0.29388416 0.52033126 0.5604815 ]
   [0.2764214  0.42552075 0.66343844]
   [0.34220418 0.5583868  0.5260926 ]
   [0.31067565 0.34819993 0.554428  ]
   [0.6270484  0.63887453 0.8193223 ]
   [0.52423406 0.17415659 0.7970908 ]
   [0.966038   0.9549861  0.08349246]
   [0.8415496  0.02023799 0.23564331]
   [0.9678454  0.9477017  0.06367252]
   [0.6121887  0.03959467 0.04618006]
   [0.99758494 0.50848573 0.03274653]
   [0.9027369  0.0288186  0.06474754]
   [0.64823127 0.69915235 0.03614818]
   [0.66322744 0.4021536  0.02487086]
   [0.34634334 0.6025924  0.01547406]
   [0.60998714 0.07581349 0.01513407]]]]
[[[[0.3102159  0.4622339  0.62637484]
   [0.28112015 0.50430197 0.6983636 ]
   [0.2585897  0.41126883 0.6770572 ]
   [0.33206066 0.54181087 0.34206742]
   [0.28830284 0.31642422 0.48371086]
   [0.6291745  0.6098215  0.7377298 ]
   [0.5431901  0.13593107 0.5878191 ]
   [0.867691   0.7713343  0.06096436]
   [0.8675066  0.01889231 0.15153836]
   [0.969

[[[[0.29073843 0.3564747  0.40462598]
   [0.26439956 0.40554354 0.6706542 ]
   [0.23938672 0.3071701  0.5656819 ]
   [0.3282246  0.44253552 0.45492527]
   [0.26656228 0.2126182  0.4960606 ]
   [0.6058513  0.5203418  0.72381765]
   [0.5063389  0.05198143 0.35101822]
   [0.87023824 0.67467797 0.10893191]
   [0.4437287  0.00187715 0.04602929]
   [0.41600582 0.53976595 0.01957892]
   [0.40203723 0.03521793 0.20144369]
   [0.99363464 0.45748755 0.04158575]
   [0.90559113 0.02713469 0.05222939]
   [0.6220693  0.57946724 0.06633915]
   [0.53427374 0.12776706 0.014875  ]
   [0.33411324 0.45802733 0.0332733 ]
   [0.40716252 0.01802274 0.03806881]]]]
[[[[0.29073843 0.3564747  0.40462598]
   [0.26439956 0.40554354 0.6706542 ]
   [0.23938672 0.3071701  0.5656819 ]
   [0.3282246  0.44253552 0.45492527]
   [0.26656228 0.2126182  0.4960606 ]
   [0.6058513  0.5203418  0.72381765]
   [0.5063389  0.05198143 0.35101822]
   [0.87023824 0.67467797 0.10893191]
   [0.4437287  0.00187715 0.04602929]
   [0.416

[[[[0.2393236  0.5483304  0.2063563 ]
   [0.22321162 0.62239254 0.19224492]
   [0.1937403  0.52813256 0.37157193]
   [0.27997392 0.68529    0.21758004]
   [0.21113646 0.52278227 0.24404095]
   [0.6154332  0.7041854  0.40248868]
   [0.40821263 0.31030428 0.43243843]
   [0.87532234 0.97267956 0.11762513]
   [0.6791754  0.04168996 0.20749344]
   [0.39687032 0.7225963  0.01912159]
   [0.22693567 0.5379646  0.05629182]
   [0.66372836 0.42187604 0.00576942]
   [0.59510255 0.15321437 0.03494515]
   [0.63292706 0.7092432  0.08567767]
   [0.47214115 0.16949241 0.02764849]
   [0.3645112  0.14731076 0.07037032]
   [0.45683143 0.13223776 0.0436757 ]]]]
[[[[0.29900414 0.6907371  0.22976312]
   [0.25616398 0.73054206 0.22586761]
   [0.24350874 0.6615431  0.16010863]
   [0.29770884 0.7195937  0.06740682]
   [0.24206166 0.5749952  0.17536062]
   [0.52104723 0.63769186 0.14584592]
   [0.41704127 0.4089051  0.25836197]
   [0.8641168  0.94390696 0.11195518]
   [0.64192367 0.1284177  0.10738054]
   [0.666

[[[[0.201592   0.6977931  0.02852405]
   [0.13698986 0.70404667 0.02351624]
   [0.527385   0.8396679  0.23005177]
   [0.11203557 0.7167758  0.02119504]
   [0.11121778 0.6105535  0.01891676]
   [0.22488582 0.694806   0.06442975]
   [0.24060166 0.52591115 0.04745344]
   [0.5209875  0.8186068  0.04290629]
   [0.632657   0.663942   0.07695405]
   [0.60626    0.84625524 0.09610135]
   [0.68350863 0.7935571  0.14111453]
   [0.7441868  0.53268373 0.06112048]
   [0.7663807  0.3650317  0.05903209]
   [0.8316376  0.59989595 0.06727657]
   [0.82853055 0.7631995  0.20892286]
   [0.81327915 0.60896224 0.03385438]
   [0.86831445 0.36831427 0.01568148]]]]
[[[[0.201592   0.6977931  0.02852405]
   [0.13698986 0.70404667 0.02351624]
   [0.527385   0.8396679  0.23005177]
   [0.11203557 0.7167758  0.02119504]
   [0.11121778 0.6105535  0.01891676]
   [0.22488582 0.694806   0.06442975]
   [0.24060166 0.52591115 0.04745344]
   [0.5209875  0.8186068  0.04290629]
   [0.632657   0.663942   0.07695405]
   [0.606

[[[[ 0.0039969   0.59115285  0.01627889]
   [-0.0036351   0.63135517  0.0124418 ]
   [-0.00785324  0.554426    0.01011772]
   [ 0.01453467  0.67358726  0.04882208]
   [ 0.01137823  0.47610766  0.0509803 ]
   [ 0.14625761  0.7689079   0.74001133]
   [ 0.17200969  0.38461918  0.8833365 ]
   [ 0.40283823  0.8261949   0.50458616]
   [ 0.46738386  0.3242311   0.7203349 ]
   [ 0.6437907   0.7571393   0.49899727]
   [ 0.736113    0.3321917   0.68720436]
   [ 0.6431322   0.7227037   0.5266262 ]
   [ 0.6455203   0.4792183   0.69205654]
   [ 0.88386905  0.83780444  0.05509594]
   [ 1.0088975   0.46433616  0.01244534]
   [ 0.6848943   0.7550943   0.04313792]
   [ 0.77754116  0.34401     0.04139987]]]]
[[[[ 0.0039969   0.59115285  0.01627889]
   [-0.0036351   0.63135517  0.0124418 ]
   [-0.00785324  0.554426    0.01011772]
   [ 0.01453467  0.67358726  0.04882208]
   [ 0.01137823  0.47610766  0.0509803 ]
   [ 0.14625761  0.7689079   0.74001133]
   [ 0.17200969  0.38461918  0.8833365 ]
   [ 0.402838

[[[[0.16996345 0.6343218  0.55943346]
   [0.14685987 0.6585598  0.5126323 ]
   [0.14761436 0.60591805 0.44810793]
   [0.1656255  0.6997704  0.49354944]
   [0.16470402 0.5736637  0.5261793 ]
   [0.30473927 0.75714433 0.7812115 ]
   [0.32551956 0.5225879  0.7285073 ]
   [0.46442556 0.846202   0.58964205]
   [0.53484994 0.49905723 0.5906154 ]
   [0.61323196 0.8453531  0.4808299 ]
   [0.6956112  0.50915015 0.7474928 ]
   [0.6921835  0.75653905 0.71593416]
   [0.6992111  0.60127294 0.8127588 ]
   [0.86815953 0.8190236  0.02627664]
   [0.88685715 0.5996659  0.02992299]
   [0.8609389  0.8792435  0.01490366]
   [0.78836143 0.54117143 0.01082781]]]]
[[[[0.17374298 0.62333894 0.54346824]
   [0.15186037 0.64525056 0.38823655]
   [0.15221915 0.5941645  0.6885569 ]
   [0.17419873 0.68389916 0.43649784]
   [0.17500874 0.5582748  0.7034944 ]
   [0.31590253 0.74916375 0.7221888 ]
   [0.33457133 0.51325744 0.7086774 ]
   [0.46439767 0.83540463 0.395559  ]
   [0.5415738  0.48633552 0.7016238 ]
   [0.600

[[[[0.22549075 0.64857876 0.4856534 ]
   [0.20631218 0.6711093  0.5416756 ]
   [0.202526   0.6230086  0.73622274]
   [0.22231029 0.7017609  0.6779639 ]
   [0.21904895 0.58408064 0.59430176]
   [0.36046097 0.7555279  0.7400424 ]
   [0.3728103  0.53175193 0.66890574]
   [0.53817606 0.81598186 0.6195351 ]
   [0.5694126  0.49733007 0.7080605 ]
   [0.69302773 0.85700935 0.62631625]
   [0.7428741  0.52093714 0.61253   ]
   [0.7212569  0.75205123 0.6890495 ]
   [0.7273185  0.5893862  0.7433748 ]
   [0.8853245  0.80319756 0.01506555]
   [0.9168942  0.5766278  0.01452478]
   [0.8600506  0.872475   0.01139281]
   [0.8291473  0.5443716  0.01337901]]]]
[[[[0.21546023 0.65076137 0.62835604]
   [0.19792396 0.67094517 0.679668  ]
   [0.19545285 0.6249219  0.67347467]
   [0.21686761 0.6995535  0.70595336]
   [0.217197   0.5849207  0.5384172 ]
   [0.35653037 0.7562362  0.7006209 ]
   [0.3707599  0.5322201  0.63627803]
   [0.5259795  0.8237587  0.7063514 ]
   [0.5686263  0.49780273 0.5725951 ]
   [0.685

[[[[0.19169793 0.63316274 0.5695425 ]
   [0.16960327 0.6563723  0.4284722 ]
   [0.16619933 0.598632   0.66728306]
   [0.20036894 0.6892004  0.56510377]
   [0.19357172 0.55223155 0.7442664 ]
   [0.3628144  0.74716246 0.79943144]
   [0.35433707 0.4859068  0.6788714 ]
   [0.58923733 0.8096618  0.69924223]
   [0.58765256 0.45794508 0.67069465]
   [0.75306    0.7934186  0.3348048 ]
   [0.7669858  0.46863398 0.68803906]
   [0.7181303  0.71860945 0.6820883 ]
   [0.731137   0.5397253  0.72529185]
   [0.84889007 0.7658734  0.10485744]
   [0.8581376  0.49125347 0.08729763]
   [0.8512301  0.8029432  0.04652891]
   [0.8334181  0.7130457  0.04685798]]]]
[[[[0.19275257 0.6440527  0.5090611 ]
   [0.1684311  0.674243   0.40237474]
   [0.16392995 0.6079389  0.6609591 ]
   [0.20127104 0.7169292  0.52739966]
   [0.18849328 0.5563692  0.60962176]
   [0.37138376 0.7597538  0.7454932 ]
   [0.36072838 0.48976034 0.82229054]
   [0.61675596 0.83106035 0.55214113]
   [0.6040268  0.4488848  0.7056644 ]
   [0.764

[[[[0.5646466  0.5381932  0.67978036]
   [0.51240563 0.58602273 0.5992768 ]
   [0.5173527  0.4870606  0.7426811 ]
   [0.5438714  0.6451502  0.526016  ]
   [0.5520947  0.42631674 0.80295193]
   [0.7445356  0.7899709  0.6734748 ]
   [0.7858538  0.3135733  0.7898386 ]
   [0.86161315 0.8813009  0.02421724]
   [0.9331445  0.25228316 0.03237603]
   [0.60720587 0.86461365 0.03293063]
   [0.8021752  0.39859515 0.00479615]
   [1.0134516  0.7346921  0.01363449]
   [0.41244483 0.33436704 0.0215424 ]
   [0.83184385 0.85905087 0.01250911]
   [0.7640364  0.34147048 0.0060592 ]
   [0.8562297  0.01591128 0.02098682]
   [0.8574821  0.02066296 0.02367531]]]]
[[[[0.5646466  0.5381932  0.67978036]
   [0.51240563 0.58602273 0.5992768 ]
   [0.5173527  0.4870606  0.7426811 ]
   [0.5438714  0.6451502  0.526016  ]
   [0.5520947  0.42631674 0.80295193]
   [0.7445356  0.7899709  0.6734748 ]
   [0.7858538  0.3135733  0.7898386 ]
   [0.86161315 0.8813009  0.02421724]
   [0.9331445  0.25228316 0.03237603]
   [0.607

[[[[0.49622178 0.45191532 0.71201074]
   [0.4293825  0.5218717  0.6704781 ]
   [0.428828   0.3884184  0.7071761 ]
   [0.46320152 0.61294746 0.70508456]
   [0.4604777  0.31613848 0.5805162 ]
   [0.6952189  0.751971   0.7920761 ]
   [0.73968136 0.18066534 0.72424746]
   [0.8615663  0.8848213  0.03822907]
   [0.9332851  0.11256724 0.02087172]
   [0.6324418  0.86982965 0.02759376]
   [0.86390746 0.00845324 0.02246474]
   [0.38671672 0.660762   0.01630516]
   [0.36129862 0.6448961  0.01628676]
   [0.855107   0.8629603  0.00660243]
   [0.7137655  0.17328298 0.00965015]
   [0.44552    0.6271233  0.01005197]
   [0.8671564  0.01064984 0.01282222]]]]
[[[[0.49622178 0.45191532 0.71201074]
   [0.4293825  0.5218717  0.6704781 ]
   [0.428828   0.3884184  0.7071761 ]
   [0.46320152 0.61294746 0.70508456]
   [0.4604777  0.31613848 0.5805162 ]
   [0.6952189  0.751971   0.7920761 ]
   [0.73968136 0.18066534 0.72424746]
   [0.8615663  0.8848213  0.03822907]
   [0.9332851  0.11256724 0.02087172]
   [0.632

[[[[0.52539015 0.52185947 0.68261933]
   [0.4659555  0.58755773 0.6281079 ]
   [0.46989128 0.45601913 0.5183574 ]
   [0.5084424  0.6562836  0.6072061 ]
   [0.5065765  0.38132024 0.7180283 ]
   [0.7047224  0.80163693 0.68765295]
   [0.75398326 0.24982886 0.788397  ]
   [0.95183814 0.9421424  0.03314467]
   [0.93461704 0.17787632 0.0233346 ]
   [0.61638904 0.86553967 0.05151241]
   [0.8492312  0.08485101 0.01817673]
   [1.0090039  0.71541405 0.01005282]
   [0.39604312 0.3431381  0.01235255]
   [0.77664685 0.8563115  0.00956903]
   [0.747453   0.2390055  0.01243275]
   [0.63819826 0.88152313 0.00695667]
   [0.85283846 0.02367221 0.01188458]]]]
[[[[0.52839524 0.52742743 0.7456578 ]
   [0.46914238 0.58921236 0.62009966]
   [0.47221026 0.46113455 0.64016306]
   [0.51173854 0.65619296 0.6559056 ]
   [0.50723684 0.38428545 0.7680251 ]
   [0.7068527  0.805884   0.6475988 ]
   [0.7544989  0.25280896 0.7310126 ]
   [0.9532529  0.94206464 0.03688278]
   [0.93387735 0.17737046 0.02190824]
   [0.610

[[[[0.42314178 0.5946048  0.7465871 ]
   [0.39039648 0.6368115  0.7182846 ]
   [0.3795123  0.5492888  0.7689055 ]
   [0.44367915 0.68212056 0.58532435]
   [0.42843455 0.47970825 0.4416733 ]
   [0.6941635  0.81226844 0.79738116]
   [0.6825878  0.32666817 0.7886627 ]
   [0.8556041  0.908348   0.07022254]
   [0.8722061  0.25868285 0.02786729]
   [0.6067041  0.87054366 0.02685369]
   [0.6508355  0.42443368 0.00268195]
   [1.0107565  0.6967964  0.00905167]
   [0.79245543 0.02785086 0.01513454]
   [0.74603385 0.8656086  0.00833159]
   [0.6653279  0.39742953 0.00869782]
   [0.46884722 0.85745335 0.0084893 ]
   [0.84913707 0.02043173 0.01704353]]]]
[[[[0.44375998 0.6062188  0.62085056]
   [0.40592074 0.6444578  0.5664678 ]
   [0.39969712 0.5608058  0.54064834]
   [0.4513193  0.6854733  0.6577238 ]
   [0.44507235 0.49244964 0.7534749 ]
   [0.7030468  0.82177114 0.79939145]
   [0.69785833 0.33745262 0.8811619 ]
   [0.8812191  0.9322371  0.03743199]
   [0.8667223  0.27135465 0.02814267]
   [0.613

[[[[0.5243772  0.61974704 0.61171305]
   [0.5011504  0.65134764 0.5047487 ]
   [0.4950243  0.5789901  0.7275728 ]
   [0.5440173  0.69077015 0.6639126 ]
   [0.5405751  0.51834154 0.62222445]
   [0.7418003  0.8320507  0.79510576]
   [0.7477304  0.3871083  0.67136884]
   [0.88194263 0.9578954  0.05402574]
   [0.8613788  0.3281963  0.05736893]
   [0.5965946  0.8642048  0.0444551 ]
   [0.6027286  0.21520486 0.06823966]
   [1.0127714  0.7391979  0.01112319]
   [1.0041062  0.4804126  0.00865654]
   [0.76848716 0.8878176  0.01910181]
   [0.7584609  0.37235206 0.04637407]
   [0.54140055 0.98242277 0.02023405]
   [0.5979486  0.20979685 0.01946132]]]]
[[[[0.525702   0.6193831  0.6619417 ]
   [0.50066984 0.6519183  0.47222757]
   [0.496841   0.57681274 0.68597174]
   [0.5476736  0.69016993 0.6630193 ]
   [0.5432751  0.5166142  0.6552107 ]
   [0.7421944  0.8297304  0.80613816]
   [0.7425663  0.38964483 0.700665  ]
   [0.7872952  0.8868322  0.02180827]
   [0.8694074  0.31178486 0.03319306]
   [0.591

[[[[0.45221156 0.62287515 0.7464731 ]
   [0.4279074  0.6588611  0.66730416]
   [0.42382067 0.5790238  0.74464697]
   [0.49298415 0.70151603 0.64418405]
   [0.48717484 0.515679   0.75336266]
   [0.71567047 0.83488774 0.7609179 ]
   [0.7232598  0.39189336 0.79835707]
   [0.88023055 0.9346976  0.11274292]
   [0.86769736 0.31751218 0.04240211]
   [0.60333586 0.8659803  0.08005819]
   [0.45804816 0.500351   0.01994692]
   [1.0178993  0.7389542  0.01065135]
   [1.0057676  0.5331347  0.00427316]
   [0.74968815 0.8853934  0.01517837]
   [0.68842554 0.4320813  0.01889794]
   [0.4789661  0.8544024  0.02302031]
   [0.4007053  0.2843135  0.01168307]]]]
[[[[0.44176897 0.6270657  0.62625945]
   [0.4187568  0.6628028  0.48775613]
   [0.41403723 0.58215004 0.46200678]
   [0.48415    0.7061247  0.4583113 ]
   [0.48297498 0.51708114 0.7193491 ]
   [0.71717775 0.8393196  0.79624915]
   [0.72367114 0.3920121  0.79203045]
   [0.90320635 0.95375556 0.04372982]
   [0.86937106 0.31906548 0.0323339 ]
   [0.626

[[[[0.442895   0.62974805 0.6447933 ]
   [0.41943178 0.66609275 0.5872423 ]
   [0.4154924  0.58178526 0.5807899 ]
   [0.4918316  0.7078969  0.63119614]
   [0.48849618 0.51281476 0.74123776]
   [0.7180228  0.829626   0.70827216]
   [0.72793925 0.37867126 0.8214192 ]
   [0.9685957  0.95748675 0.06139937]
   [0.8666286  0.31378832 0.01900592]
   [0.5995685  0.8637165  0.09448287]
   [0.45759416 0.49604425 0.01911952]
   [1.0183569  0.7595098  0.0089251 ]
   [0.36295652 0.7579238  0.01604189]
   [0.71282184 0.8702354  0.0060347 ]
   [0.6860251  0.4320216  0.01956802]
   [0.48354396 0.86053336 0.02541545]
   [0.50978065 0.66430306 0.00425666]]]]
[[[[0.44672    0.6244014  0.68812406]
   [0.4219066  0.66076076 0.5863666 ]
   [0.41890532 0.5767535  0.71074986]
   [0.48990726 0.7059959  0.5469785 ]
   [0.49203885 0.5103035  0.7075567 ]
   [0.716948   0.82970893 0.7007416 ]
   [0.72713125 0.38278133 0.8443792 ]
   [0.9670794  0.95688987 0.06020357]
   [0.86653626 0.3156281  0.02042058]
   [0.599

[[[[0.49253008 0.6515714  0.73497343]
   [0.46036762 0.69173807 0.6311474 ]
   [0.45739454 0.6031151  0.59591585]
   [0.517726   0.73786306 0.61049265]
   [0.511567   0.5349069  0.77622634]
   [0.7419598  0.86169124 0.83598995]
   [0.74169934 0.40457803 0.82218874]
   [0.8426621  0.91899985 0.0247204 ]
   [0.8667191  0.33843088 0.02452739]
   [0.60180056 0.8666541  0.07184986]
   [0.53489304 0.5024258  0.0157565 ]
   [1.0213492  0.847044   0.00906446]
   [0.40615985 0.8061587  0.01276376]
   [0.79269546 0.8964886  0.01776424]
   [0.6916424  0.47531307 0.00677883]
   [0.5142666  0.81854075 0.01590088]
   [0.40010104 0.28529745 0.00953614]]]]
[[[[0.4776817  0.678184   0.49236205]
   [0.45239025 0.71356857 0.7084511 ]
   [0.447181   0.6271651  0.60514206]
   [0.52760124 0.75243354 0.56711113]
   [0.51708835 0.5511325  0.65430117]
   [0.7444369  0.8637701  0.83793366]
   [0.7415177  0.41392052 0.75275695]
   [0.9625322  0.9683017  0.05055695]
   [0.8653056  0.34215212 0.03128491]
   [0.594

[[[[0.46673018 0.70683646 0.65459234]
   [0.45088792 0.7421891  0.73130864]
   [0.43829557 0.6582133  0.6445222 ]
   [0.5429728  0.7650683  0.38512838]
   [0.5148964  0.5723009  0.53053224]
   [0.7546567  0.86314934 0.6177889 ]
   [0.74775875 0.42451584 0.80183303]
   [0.95687383 0.9713232  0.04665079]
   [0.86275506 0.34742326 0.02865101]
   [0.5859601  0.8633845  0.08611796]
   [0.527696   0.52241147 0.00779744]
   [0.4360271  0.49873054 0.01905581]
   [0.37779757 0.52291656 0.02366457]
   [0.7925005  0.90562415 0.02466358]
   [0.80313396 0.7184769  0.02925132]
   [0.5364381  0.86018866 0.10086995]
   [0.506896   0.7524395  0.0108682 ]]]]
[[[[0.46673018 0.70683646 0.65459234]
   [0.45088792 0.7421891  0.73130864]
   [0.43829557 0.6582133  0.6445222 ]
   [0.5429728  0.7650683  0.38512838]
   [0.5148964  0.5723009  0.53053224]
   [0.7546567  0.86314934 0.6177889 ]
   [0.74775875 0.42451584 0.80183303]
   [0.95687383 0.9713232  0.04665079]
   [0.86275506 0.34742326 0.02865101]
   [0.585

[[[[0.47491318 0.7139226  0.61855614]
   [0.4573793  0.7473425  0.35367984]
   [0.44731593 0.6602207  0.7187842 ]
   [0.53923523 0.77134556 0.54459506]
   [0.5192641  0.5747187  0.6480689 ]
   [0.75731605 0.87045133 0.76962805]
   [0.7522845  0.42490828 0.8199793 ]
   [0.85025686 0.9537954  0.01074694]
   [0.8659825  0.35244414 0.03017022]
   [0.5863831  0.8658911  0.05459981]
   [0.73324656 0.47296315 0.00746785]
   [1.0213677  0.8477142  0.00976796]
   [0.39598963 0.5227693  0.0226388 ]
   [0.69397616 0.9563474  0.00701862]
   [0.8105129  0.7192706  0.02376422]
   [0.53072333 0.8599658  0.0611315 ]
   [0.51565844 0.7890862  0.00737406]]]]
[[[[0.47573018 0.71846366 0.6773336 ]
   [0.45685562 0.751266   0.36537686]
   [0.44900227 0.6628383  0.64118505]
   [0.5385457  0.77206063 0.56180644]
   [0.52027553 0.5749855  0.65692663]
   [0.75767446 0.8707265  0.77937955]
   [0.75196874 0.42116892 0.78739357]
   [0.9576137  0.97061557 0.04846008]
   [0.8657727  0.35215494 0.02845125]
   [0.582

[[[[0.48322368 0.7010639  0.6690807 ]
   [0.4618406  0.7356245  0.5483726 ]
   [0.4516816  0.64601314 0.4231706 ]
   [0.53961354 0.7666387  0.43626395]
   [0.5232465  0.5658022  0.550543  ]
   [0.7567121  0.86719894 0.73797274]
   [0.7480601  0.4221983  0.79922485]
   [0.9575387  0.97086704 0.04993491]
   [0.8640503  0.349941   0.03025927]
   [0.58779895 0.868495   0.10172686]
   [0.5383015  0.51246464 0.00647465]
   [0.45735174 0.84117883 0.01821805]
   [0.3948998  0.52441067 0.02531804]
   [0.7913871  0.9061546  0.02398978]
   [0.8183975  0.71249676 0.02309611]
   [0.536186   0.86577463 0.05761578]
   [0.51339674 0.7919921  0.01061707]]]]
[[[[0.4928609  0.6761694  0.756065  ]
   [0.46631104 0.71401423 0.70236886]
   [0.4620683  0.6243809  0.5121485 ]
   [0.53811383 0.759907   0.5367073 ]
   [0.5320592  0.5522271  0.7383523 ]
   [0.7552129  0.8702948  0.7891629 ]
   [0.7469827  0.4233998  0.7576611 ]
   [0.95633304 0.9711     0.04907015]
   [0.8668939  0.34382546 0.0269648 ]
   [0.578

[[[[0.5094616  0.6613709  0.750385  ]
   [0.47263002 0.70036757 0.69168997]
   [0.4705903  0.6066896  0.70562863]
   [0.52424824 0.7488185  0.57390445]
   [0.5250416  0.5353452  0.74391806]
   [0.75443447 0.8649742  0.7304909 ]
   [0.75701725 0.39923677 0.81492937]
   [0.85928595 0.9522792  0.01203139]
   [0.8670046  0.3382851  0.02010638]
   [0.59635806 0.865761   0.04605895]
   [0.7284958  0.43400073 0.00517579]
   [1.0183034  0.8477224  0.01058256]
   [0.3994088  0.50208545 0.01498988]
   [0.7853278  0.8999278  0.01867912]
   [0.7682225  0.39192793 0.01489228]
   [0.5873982  0.980183   0.01395849]
   [0.4012226  0.28913736 0.01047821]]]]
[[[[0.5094616  0.6613709  0.750385  ]
   [0.47263002 0.70036757 0.69168997]
   [0.4705903  0.6066896  0.70562863]
   [0.52424824 0.7488185  0.57390445]
   [0.5250416  0.5353452  0.74391806]
   [0.75443447 0.8649742  0.7304909 ]
   [0.75701725 0.39923677 0.81492937]
   [0.85928595 0.9522792  0.01203139]
   [0.8670046  0.3382851  0.02010638]
   [0.596

[[[[0.53052187 0.66311646 0.7444391 ]
   [0.49177563 0.7078066  0.5535882 ]
   [0.49246272 0.6100384  0.73516476]
   [0.5486441  0.7618524  0.6730045 ]
   [0.5483246  0.5336573  0.7600984 ]
   [0.7564908  0.8708345  0.8308305 ]
   [0.7582718  0.4075507  0.83583426]
   [0.85724795 0.95530677 0.01453598]
   [0.8699216  0.32457188 0.01317826]
   [0.58296883 0.8587126  0.05321618]
   [0.7437641  0.44899654 0.00510888]
   [0.46837395 0.84728944 0.01756179]
   [0.42312098 0.4835834  0.01769858]
   [0.8041057  0.91557515 0.02622304]
   [0.75106025 0.4099617  0.02006555]
   [0.5404452  0.8400972  0.02369381]
   [0.5343106  0.78098387 0.00900818]]]]
[[[[0.5358838  0.6615178  0.72469914]
   [0.49566108 0.70724934 0.48198584]
   [0.49380502 0.60637164 0.72809255]
   [0.5497302  0.76355577 0.68986666]
   [0.54670274 0.53062284 0.7779701 ]
   [0.7572271  0.8708377  0.83329153]
   [0.7622198  0.39981532 0.7990611 ]
   [0.87089413 0.95717496 0.01847866]
   [0.8862697  0.32062578 0.01408342]
   [0.588

[[[[5.3862220e-01 6.7833626e-01 7.3294616e-01]
   [4.9488375e-01 7.2239959e-01 6.3206041e-01]
   [4.8865694e-01 6.1834311e-01 6.2901729e-01]
   [5.4833543e-01 7.6918352e-01 6.6618460e-01]
   [5.3884959e-01 5.3570193e-01 6.7778647e-01]
   [7.6973987e-01 8.8304985e-01 6.9218200e-01]
   [7.5218344e-01 4.0234229e-01 7.6379037e-01]
   [9.5582676e-01 9.7817242e-01 4.5655064e-02]
   [8.8052744e-01 3.2651466e-01 1.4950049e-02]
   [5.8865488e-01 8.6121219e-01 3.7217595e-02]
   [7.8302038e-01 4.8799857e-01 5.2528181e-03]
   [4.8787123e-01 8.6531603e-01 2.0301057e-02]
   [4.2245960e-01 4.8357618e-01 1.8474193e-02]
   [7.9595923e-01 9.3423319e-01 1.5821680e-02]
   [7.3715848e-01 4.1315231e-01 1.1306987e-02]
   [6.0239542e-01 1.0033383e+00 9.1378465e-03]
   [7.0743459e-01 6.3470823e-01 7.1342342e-04]]]]
[[[[0.5280204  0.6871048  0.5731384 ]
   [0.48713738 0.7297915  0.6465696 ]
   [0.48119462 0.62786865 0.61886775]
   [0.5402607  0.7710494  0.5341327 ]
   [0.535702   0.53920174 0.6441492 ]
   [0.76

In [28]:
keypoints_with_scores.shape #For testing (this is as expected from the documentation)

(1, 1, 17, 3)

In [29]:
# Outputs
# A float32 tensor of shape [1, 1, 17, 3].
        # The first two channels of the last dimension represents the yx coordinates (normalized to image frame, i.e. range in [0.0, 1.0]) of the 17 keypoints 
        #(in the order of: [nose, left eye, right eye, left ear, right ear, left shoulder, right shoulder, left elbow, right elbow, left wrist, right wrist, left hip, right hip, left knee, right knee, left ankle, right ankle]).
        # The third channel of the last dimension represents the prediction confidence scores of each keypoint, also in the range [0.0, 1.0].

In [30]:
#Using the order of body parts given in the above cell
right_eye = keypoints_with_scores[0][0][2]
left_elbow = keypoints_with_scores[0][0][7]
left_elbow #printing one of them out to see what it looks like

array([0.88844776, 0.96147466, 0.02412108], dtype=float32)

In [31]:
np.array(left_elbow[:2]*[480,640]).astype(int) #standardized coordinates to frame coordinates

array([426, 615])

In [32]:
frame.shape

(480, 640, 3)